name: Inference Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Tests
      run: pytest

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Train Model
      run: python src/train.py
    - name: Upload model
      uses: actions/upload-artifact@v3
      with:
        name: model
        path: model_train.pkl

  inference:
    runs-on: ubuntu-latest
    needs: train
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Download model
      uses: actions/download-artifact@v3
      with:
        name: model
        path: .
    - name: Run inference
      run: python src/inference.py
